version: '3.1'

services:
  mongo:
    image: mongo
    container_name: chat_mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network
  mongo-express:
    image: mongo-express
    container_name: chat_mongo_express
    restart: always
    links:
      - mongo
    networks:
      - mongo-compose-network
    ports:
      - 8081:8081
  redis:
    image: redis
    container_name: chat_redis
    ports:
      - 6379:6379
  
networks: 
    mongo-compose-network:
      driver: bridge